config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user_choices#new'

  get 'getavailable', to: "collections#getavailable"
  patch 'available', to: 'collections#available'
  get 'getunavailable', to: "collections#getunavailable"
  patch 'unavailable', to: 'collections#unavailable'

  resources :collections
  resources :items
  resources :votes
  resources :user_choices
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_one_attached :photo

  has_many :items
  has_many :user_choices
  belongs_to :user

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]
  before_action do
    authorize(Collection)
  end

  # SHOW => RESULTS PAGES
  def show
    no_zero_votes = @collection.items.select do |item|
      item.votes.count >= 1
    end
    @items = no_zero_votes.sort_by { |item| item.votes.count }.reverse
  end

  def new
    @collections = Collection.all.order(created_at: :desc)
    @collection = Collection.new
  end

  def create
    active_false
    @collection = Collection.create(name: collection_params[:name], photo: collection_params[:photo], user: current_user, active: false)
    add_shoes_to_collection
    redirect_to edit_collection_path(@collection)
  end

  #desativando collection a medida que crio uma nova
  def active_false
    unless Collection.last == nil
    last_collection = Collection.last
    last_collection.active = false
    last_collection.save
    end
  end

  def available
    @collection = Collection.last
    @collection.active = true
    @collection.save

    redirect_to root_path
  end

  def getavailable
    available
  end

  def unavailable
    @collection = Collection.last
    @collection.active = false
    @collection.save

    redirect_to root_path
  end

  def getunavailable
    unavailable
  end


  def edit
    @collections = Collection.all.order(created_at: :desc)
    @items = Item.all.where(collection: @collection)
    @items = @items.sort_by { |item| item.name }
    @items = @items.uniq { |h| h[:name] }

    @items.each do |item|
      @item = item
    end

  end

  def update
    if collection_params[:photos]
      add_shoes_to_collection
    end
    if collection_params[:photo]
    @collection.update(collection_params)
    end
    redirect_to edit_collection_path(@collection)
  end

  def destroy
    if @collection.user_choices != []
      @collection.user_choices.each do |choice|
        choice.votes.each do |vote|
          vote.delete
        end
        choice.delete
      end
    end

    @collection.items.each do |item|
      item.delete
    end
    @collection.delete

    redirect_to new_collection_path
  end

  private

  def add_shoes_to_collection
    collection_params[:photos].each do |photo|
      Item.create(collection: @collection,
                  name: photo.original_filename,
                  photo: photo)
    end
  end

  def collection_params
    params.require(:collection).permit(:name, :photo, photos: [])
  end

  def set_collection
    @collection = Collection.find(params[:id])
  end

end

app/views/collections/edit.html.erb
<div class="display-grid" style="height: 100vh">

  <div class="scrollbar" style="padding-left: 120px; border-right: 1px solid black;">
    <div style="padding-top: 110px;">
      <h1><b>campanhas</b></h1>
      <%= link_to "CRIAR NOVA CAMPANHA", new_collection_path, class: "botao2" %>
      <br>
      <br>

      <% @collections.each do |collection| %>

        <div style="width: 80%; padding: 12px; background-color: #F4F4EE; border-radius: 4px;">
           <h3><%= collection.name %> </h3><br>
           <p><%= link_to "fotos", edit_collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "add. fotos", edit_collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "resultados", collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "deletar", collection_path(collection), method: :delete, data: { confirm: "DELETAR CAMPANHA?" }, class: "btn-sm-bl" %></p>
           <% if collection == Collection.last %>
           <hr>
           <p> <% if collection.active == false %>  <%= link_to "ATIVAR", getavailable_path(collection), class: "btn-sm-bl" %>  <% else %> <%= link_to "DESATIVAR", getunavailable_path(collection), class: "btn-sm-bl" %> <% end %> </p>
            <% end %>

        </div>
         <br>
      <% end %>
    </div>
  </div>



  <div class="scrollbar" style="margin-top: 120px; padding-left: 48px; width: 90%;">

      <div >
      <h2><b> <%= @collection.name.upcase %></b></h2>
      </div>

      <div style="border: 1px solid black; width: 90%; border-radius: 20px; padding: 24px; margin-top:32px;">
        <h4 style="padding-bottom: 0; margin-bottom: 0;"><b>adicione novas fotos</b></h4>
        <br>
        <%= simple_form_for :collection, url: collection_path(@collection), method: :patch do |f| %>
        <% unless @collection.photo.attached? %>
        <%= f.input :photo, label: 'banner', as: :file %>
        <% end %>
        <%= f.input :photos, label: 'sapatos', as: :file, input_html: { multiple: true } %>
        <br>
        <%= button_tag "SALVAR", class: "button", role: "button", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>".html_safe} %>
        <% end %>
      </div>


    <div style="margin-top: 36px;">
      <hr>
      <h4><b>fotos adicionadas:</b></h4>
      <div class="mini-fotos">
        <% @items.each do |item| %>
          <div>
            <p class="small-text-x"> <%= link_to "×",
              item_path(item),
              method: :delete,
              data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> </p>
          <%= cl_image_tag item.photo.key, class: "img-shoe" %>
          <p class="small-text">
             <% if item.name[-3..-1] == 'JPG'%>
                <%= item.name.split('.JPG')[0]  %>
             <% elsif item.name[-3..-1] == 'jpg'%>
                <%= item.name.split('.jpg')[0]  %>
             <% elsif item.name[-3..-1] == 'PNG'%>
                <%= item.name.split('.PNG')[0]  %>
             <% elsif item.name[-3..-1] == 'png'%>
                <%= item.name.split('.png')[0]  %>
             <% elsif item.name[-4..-1] == 'JPEG'%>
                <%= item.name.split('.JPEG')[0]  %>
             <% elsif item.name[-4..-1] == 'jpeg'%>
                <%= item.name.split('.jpeg')[0]  %>
            <% end %> </p>
          </div>
        <% end %>
      </div>
    </div>



  </div>


</div>

app/views/collections/new.html.erb
<div class="display-grid" style="height: 100vh">

  <div class="scrollbar" style="padding-left: 120px; border-right: 1px solid black;">
    <div style="padding-top: 110px;">
      <h1><b>campanhas</b></h1>

      <br>
      <br>

      <% @collections.each do |collection| %>

        <div style="width: 80%; padding: 12px; background-color: #F4F4EE; border-radius: 4px;">
           <h3><%= collection.name %> </h3><br>
           <p><%= link_to "fotos", edit_collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "add. fotos", edit_collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "resultados", collection_path(collection), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> <%= link_to "deletar", collection_path(collection), method: :delete, data: { confirm: "DELETAR CAMPANHA?" }, class: "btn-sm-bl" %></p>
           <% if collection == Collection.last %>
           <hr>
           <p> <% if collection.active == false || nil %>  <%= link_to "ATIVAR", getavailable_path(collection), class: "btn-sm-bl" %>  <% else %> <%= link_to "DESATIVAR", getunavailable_path(collection), class: "btn-sm-bl" %> <% end %> </p>
            <% end %>

         </div>
         <br>
      <% end %>
    </div>
  </div>






  <div class="scrollbar" style="margin-top: 110px; padding-left: 60px; width: 60%;">

    <h1><b>crie uma nova <br> campanha</b></h1>
    <br>

    <%= simple_form_for(@collection) do |f| %>
      <%= f.input :name, label: 'nome da campanha:' %>
      <%= f.input :photo, label: 'banner:', as: :file %>
      <%= f.input :photos, label: 'sapatos:', as: :file, input_html: { multiple: true } %>
      <br>
      <%= button_tag "SALVAR", class: "button", role: "button", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>".html_safe} %>

    <% end %>

  </div>



</div>

app/views/collections/show.html.erb
<div class="fixed-title" style="padding-bottom: 24px; border-bottom: 1px solid black;">
  <div style="padding-left: 120px;">
    <h1><b>resultados:</b></h1>
      <ul class="nav nav-pills" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="botao2" id="client-tab" data-toggle="tab" href="#client" role="tab" aria-controls="client" aria-selected="false">POR CLIENTE</a>
        </li>
        <li class="nav-item">
          <a class="botao2" id="product-tab" data-toggle="tab" href="#product" role="tab" aria-controls="product" aria-selected="true">POR PRODUTO</a>
        </li>
      </ul>
  </div>
</div>


<div class="tab-content" style="margin-top: 200px; padding-left: 96px; padding-right: 96px; padding-top: 36px;">

    <div class="tab-pane" id="product" role="tabpanel" aria-labelledby="product-tab">
    <% @items.each do |item| %>
      <div class="row" style="padding-right: 36px;">
        <div class="col-3">
          <%= cl_image_tag item.photo.key, class: "img-shoe" %>
        </div>
        <div class="col-3">
          <h5>
            <% if item.name[-3..-1] == 'JPG'%>
                <%= item.name.split('.JPG')[0]  %>
             <% elsif item.name[-3..-1] == 'jpg'%>
                <%= item.name.split('.jpg')[0]  %>
             <% elsif item.name[-3..-1] == 'PNG'%>
                <%= item.name.split('.PNG')[0]  %>
             <% elsif item.name[-3..-1] == 'png'%>
                <%= item.name.split('.png')[0]  %>
             <% elsif item.name[-4..-1] == 'JPEG'%>
                <%= item.name.split('.JPEG')[0]  %>
             <% elsif item.name[-4..-1] == 'jpeg'%>
                <%= item.name.split('.jpeg')[0]  %>
            <% end %>
          </h5>
        </div>
        <div class="col-6 text-right">
          <h5><%= item.votes.count %></h5>
        </div>
      </div>
      <hr>
    <% end %>
    </div>


  <div class="tab-pane active" id="client" role="tabpanel" aria-labelledby="client-tab">
    <div class="tab-pane" id="product" role="tabpanel" aria-labelledby="product-tab">
    <% @collection.user_choices.each do |user_choice| %>
      <% if user_choice.user.admin == false %>


    <div class="row" style="margin-bottom: 18px;">

      <div class="col-4" style="padding-right: 24px;">

        <h3> <%= link_to "#{user_choice.user.name} #{user_choice.user.surname}", user_path(user_choice.user) %>  </h3><br>
        <% if user_choice.user.instagram %>
        <% instagram = user_choice.user.instagram.upcase.gsub('@','').gsub(/(https:\/\/)*(www.)*(instagram.com)\//, '').gsub('/','') %>
        <p>instagram:<%= link_to "@#{instagram.downcase}", "https://www.instagram.com/#{instagram}", target:'_blank' %> <br>
        <% end %>
        <% if user_choice.user.email %>
        e-mail: <%= user_choice.user.email.downcase %> <br>
        <% end %>
        <% if user_choice.user.numer %>
        numeração: <%= user_choice.user.numer %> </p>
        <% end %>

        <p>políticas de uso de dados: <% if user_choice.user.politics == true %> concorda  <% else %>  não concorda <% end %> </p>

      </div>

      <div class="col-7 results-grid">
        <% user_choice.items.each do |item| %>
          <div> <%= cl_image_tag item.photo.key, class: "img-shoe" %>
          <p style="font-size: 9pt">
            <% if item.name[-3..-1] == 'JPG'%>
                <%= item.name.split('.JPG')[0]  %>
             <% elsif item.name[-3..-1] == 'jpg'%>
                <%= item.name.split('.jpg')[0]  %>
             <% elsif item.name[-3..-1] == 'PNG'%>
                <%= item.name.split('.PNG')[0]  %>
             <% elsif item.name[-3..-1] == 'png'%>
                <%= item.name.split('.png')[0]  %>
             <% elsif item.name[-4..-1] == 'JPEG'%>
                <%= item.name.split('.JPEG')[0]  %>
             <% elsif item.name[-4..-1] == 'jpeg'%>
                <%= item.name.split('.jpeg')[0]  %>
            <% end %>
           </p>
          </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <hr>
    <% end %>
    </div>
  </div>


</div>