config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user_choices#new'

  get 'getavailable', to: "collections#getavailable"
  patch 'available', to: 'collections#available'
  get 'getunavailable', to: "collections#getunavailable"
  patch 'unavailable', to: 'collections#unavailable'

  resources :collections
  resources :items
  resources :votes
  resources :user_choices
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_choice.rb
class UserChoice < ApplicationRecord
  belongs_to :collection
  belongs_to :user
  has_many :votes
  has_many :items, through: :votes
end

app/controllers/user_choices_controller.rb
class UserChoicesController < ApplicationController

  def new
    authorize UserChoice

    @last_active_collection = Collection.where(active: true).last
    @last_collection = Item.all.where(collection: @last_active_collection).sort_by { |item| item.name }.uniq { |h| h[:name] }
    @user_voted = UserChoice.where(collection: @last_active_collection, user: current_user)
  end

  def create
    authorize UserChoice
    set_user_choice
    last_active_collection = Collection.where(active: true).last
    @last_collection = Item.all.where(collection: last_active_collection)

    user_choice_params[:vote].each do |vote|
      # image_code = vote.split('production/')[1][0..-5]
      image_code = vote.split('development/')[1][0..-5]
      matched = @last_collection.select { |shoe| shoe.photo.key == image_code }
      voted_shoe = matched.first
      Vote.create(user_choice: @user_choice, item: voted_shoe)
    end
    redirect_to user_choice_path(@user_choice)
  end

  def show
    authorize UserChoice
    set_user_choice

    @votes = current_user.user_choices[-1].votes
  end

  def edit
    authorize UserChoice

    @last_active_collection = Collection.where(active: true).last
    @last_collection = Item.all.where(collection: @last_active_collection).sort_by { |item| item.name }.uniq { |h| h[:name] }
    @user_voted = UserChoice.where(collection: @last_active_collection, user: current_user)

    @votes = current_user.user_choices[-1].votes
  end

  def update
  end

  private

  def set_user_choice
    @user_choice = UserChoice.find_or_create_by(user: current_user, collection: Collection.last)
  end

  def user_choice_params
    params.require(:user_choice).permit(vote: [])
  end
end

app/views/user_choices/edit.html.erb
<div class="row">

  <div class="col-12 col-md-5">
    <div style="padding-left: 10%; padding-right: 10%;">
      <h3 style="margin-top: 98px;"><b>OI, <%= current_user.name.upcase %>.</b></h3>
      <p>AQUI VOCÊ PODE EDITAR SUA SELEÇÃO.</p>
      <hr>
      <h3> <b>remova itens: </b></h3>
        <div class="mini-fotos-edit" style="width: 50%;">
         <% @votes.each do |vote| %>
          <div>
            <p class="small-text-edit"> <%= link_to "×",
                vote_path(vote),
                method: :delete, data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %> </p>
                <%= cl_image_tag vote.item.photo.key, width: 104, class: "img-shoe-edit" %>
          </div>
        <% end %>
      </div>
      <hr>
      <% user_choice = current_user.user_choices[-1] %>
      <%= link_to "concluir remoções", user_choice_path(user_choice), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %>
    </div>
  </div>

  <div class="col-12 col-md-7" style="border-left: 1px solid black;">
    <div class="second-column">
    <h3 style="text-align: center;"> ou selecione novos:</h3>
      <div class="main-form">

        <% unless Collection.last == nil %>
        <% if  Collection.last.active == true %>
          <%= simple_form_for :user_choice, url: '/user_choices' do |f| %>
            <%= f.input :vote,
                        collection: @last_collection.map { |item| cl_image_tag item.photo.key, width: 380 },
                        as: :check_boxes,
                        required: true,
                        include_blank: false,
                        include_hidden: false %>
                        <br>
            <%= button_tag "ENVIAR", class: "form-button", role: "button", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i> ".html_safe} %>
        <% end %>
      <% end %>
      <% end %>
    </div>
    </div>
  </div>

</div>

app/views/user_choices/new.html.erb
<div class="homecontainer">


    <% unless Collection.last == nil %>
    <% unless Collection.last.active == false %>
      <div class="row justify-content-center banner">
        <% if @last_active_collection.photo.attached? %>
      <%= cl_image_tag @last_active_collection.photo.key %>
          <% end %>
      <% end %>
      <% end %>
      </div>
      <br>
        <div style="margin-left: 64px; margin-right: 56px;">
      <% if current_user.admin == true %>
        <h2>equipe Luiza Barcelos, </h2>
        <h4 style="font-weight: lighter;">acesse seu painel de administração ↗ </h4>
      <% else %>
        <h2 style="font-size: 42px;"><b>OLÁ, <%= current_user.name.upcase %>.</b></h2>
        <% if Collection.last == nil || Collection.last.active == false || nil %>
        <br>
          <h3>neste momento, não há coleções disponíveis. </h3>
        <% else %>
          <h3> <b> selecione seus itens favoritos: </b></h3>
        <% end %>
      <% end %>
      </div>
</div>

  <br>

<div class="main-form">

  <% unless Collection.last == nil %>
  <% if  Collection.last.active == true %>
      <%= simple_form_for :user_choice, url: '/user_choices' do |f| %>
        <%= f.input :vote,
                    collection: @last_collection.map { |item| cl_image_tag item.photo.key, width: 380 },
                    as: :check_boxes,
                    required: true,
                    include_blank: false,
                    include_hidden: false %>
                    <br>
      <%= button_tag "ENVIAR", class: "form-button", role: "button", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>".html_safe} %>
      <% end %>
  <% end %>
  <% end %>

  </div>

app/views/user_choices/show.html.erb
<div class="container">
  <div class="fixed-title">
    <h3>Obrigada,  <%= current_user.name.upcase %>. </h3>
    <h3 style="margin-bottom: 16px;">→ itens enviados:</h3>
    <%= link_to "editar", edit_user_choice_path(@user_choice), class: "botao2", data: { disable_with: "<i class='fas fa-spinner fa-spin'></i>"} %>

    <br>
    <p style="color: white;">—</p>
  </div>

  <div style="margin-top: 145px">
    <% @votes.each do |vote| %>
    <%= cl_image_tag vote.item.photo.key, width: 112, class: "img-shoe-edit" %>
    <% end %>
  </div>
</div>