config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'user_choices#new'

  get 'getavailable', to: "collections#getavailable"
  patch 'available', to: 'collections#available'
  get 'getunavailable', to: "collections#getunavailable"
  patch 'unavailable', to: 'collections#unavailable'

  resources :collections
  resources :items
  resources :votes
  resources :user_choices
  resources :users, only: [:index, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed-top navbar-expand-sm navbar-light">
  <div class="navbar-row">

    <%= link_to root_path do %>
    <%= image_tag "logo_luiza_barcelos.png", id: "logo" %>
    <% end %>

      <% if user_signed_in? %>


      <ul class="navbar-inline-list">
        <% if policy(Collection).new? %>
          <li> <%= link_to "admin", new_collection_path, class: "botao2" %> </li>
        <% end %>
        <li> <%= link_to "sair", destroy_user_session_path, method: :delete, class: "botao2" %></li>
        <% if current_user.user_choices != [] && current_user.user_choices[-1].collection == Collection.where(active: true).last %>
        <% collection = current_user.user_choices[-1].id %>
        <% unless policy(Collection).new? %>
        <li> <%= link_to "meus itens", user_choice_path(collection), class: "botao2" %> </li>
        <% end %>

        <% end %>
      </ul>


      <% else %>


      <ul class="navbar-inline-list">
        <% if controller_name != 'sessions' %>
        <%= link_to "login", new_session_path(resource_name), class: "botao2" %>
        <% end %>
        <% if devise_mapping.registerable? && controller_name != 'registrations' %>
        <%= link_to "cadastro", new_registration_path(resource_name), class: "botao2" %>
        <% end %>
      </ul>

      <% end %>

  </div>
</div>